console.log('╔════════════════════════════════════════════════════════════╗');
console.log('║   🚨 HYPERLOCAL INCIDENT REPORTING MAP                    ║');
console.log('║   Hackathon Project - Civic Tech Application              ║');
console.log('╚════════════════════════════════════════════════════════════╝');
console.log('');
console.log('📋 QUICK START CHECKLIST:');
console.log('');
console.log('  ✓ Node.js installed');
console.log('  ✓ Dependencies installed (npm install)');
console.log('  ? MongoDB connected?');
console.log('');
console.log('📍 MONGODB SETUP:');
console.log('');
console.log('  Option 1 - Local MongoDB:');
console.log('    - Install from: https://www.mongodb.com/try/download/community');
console.log('    - Start MongoDB service');
console.log('    - Connection: mongodb://localhost:27017/incident-reporting');
console.log('');
console.log('  Option 2 - MongoDB Atlas (Recommended for Hackathons):');
console.log('    - See MONGODB_SETUP.md for detailed instructions');
console.log('    - Free cloud database, no installation needed');
console.log('    - Update MONGODB_URI in .env file');
console.log('');
console.log('🚀 TO START THE APPLICATION:');
console.log('');
console.log('    npm start');
console.log('');
console.log('📱 THEN OPEN IN BROWSER:');
console.log('');
console.log('    http://localhost:3001');
console.log('');
console.log('💡 FEATURES:');
console.log('  • Real-time incident reporting');
console.log('  • Live map with Leaflet.js & Geoapify');
console.log('  • WebSocket communication (Socket.IO)');
console.log('  • Geospatial database queries');
console.log('  • Community confirmations');
console.log('  • Weather data integration');
console.log('  • Beautiful, responsive UI');
console.log('');
console.log('🎯 HACKATHON DEMO TIPS:');
console.log('  1. Open the app on two devices/browsers');
console.log('  2. Report an incident on one device');
console.log('  3. Watch it appear in real-time on the other!');
console.log('  4. Demonstrate the confirmation feature');
console.log('');
console.log('📚 NEED HELP?');
console.log('  • Read README.md for full documentation');
console.log('  • Check MONGODB_SETUP.md for database setup');
console.log('  • All API endpoints documented in README.md');
console.log('');
console.log('════════════════════════════════════════════════════════════');
console.log('');
